### ISSUE TITLE
all_touched arg to make_geocube?

### ISSUE THREAD

**Issue by raybellwaves** [corteva/geocube#108]
Nice to see the solution here https://github.com/corteva/geocube/discussions/97#discussioncomment-2502293

Wonder if there is any interested in adding `all_touched` as an arg to `make_geocube` to simply this for users?

For example a user can't use `all_touched` and `rasterize_function` at the same time. and `all_touched` is a thin wrapper to `partial(rasterize_image, all_touched=True)`

**Comment by snowman2** [comment]
There are several different functions that could be applied to rasterize data:
- https://corteva.github.io/geocube/stable/geocube.html#rasterize
- https://corteva.github.io/geocube/stable/examples/rasterize_point_data.html

`all_touched` is specific to the `rasterize_image` and does not apply to the other functions. I am concerned adding this could cause confusion if a different function is used in the rasterization process.

**Comment by raybellwaves** [comment]
Agreed. It's not quite as easy to slot in as I imagined
