### ISSUE TITLE
ImportError: cannot import name 'NDArray' from 'numpy.typing'

### ISSUE THREAD

**Issue by DawnMKing** [corteva/geocube#113]
This code used to work, and now suddenly it is not importing a package within the geocube package.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/21011198/176515421-0d2bf3af-d942-4592-9b9e-c06d6ac67053.png">

**Comment by snowman2** [comment]
Are you able to provide the version of numpy and geocube you are using?

**Comment by snowman2** [comment]
Without further information, it is difficult to assist. I recommend upgrading numpy & geocube. If that does not solve this issue and you can provide more information about your development environment, please add a comment.
