### ISSUE TITLE
Rasterization as DataArray 

### ISSUE THREAD

**Issue by Meresmata** [corteva/geocube#128]
The function `geocube.rasterize.rasterize_image` returns a numpy array. 
It would be nice if it also could be returned as a DataArray/Dataset. The extent, crs and resolution were already given as parameters.
Or is there a simple wrapper for that?

**Comment by snowman2** [comment]
Are you asking about [make_geocube](https://corteva.github.io/geocube/stable/geocube.html#geocube.api.core.make_geocube)?

**Comment by snowman2** [comment]
Closing as I believe this issue has been addressed.
