### ISSUE TITLE
Setting a name for the value column in vectorize

### ISSUE THREAD

**Issue by Imanflow** [corteva/geocube#164]
When using vectorize, the resulting GDF has None as column name, creating issues when trying to save to a file. 

It would be nice to set a defaul value. VALUES, for instance, or whatever that is not None. 

I could do it.

**Comment by snowman2** [comment]
It derives the name from the DataArray. You can set the name on the DataArray property.

```pyrhon
da.name = "my_data"
vectorize(da)
```

**Comment by Imanflow** [comment]
Oh I see. Thanks for the info

**Comment by snowman2** [comment]
I think that this could be highlighted better. Thoughts about adding a warning if the DataArray name is None?
