### ISSUE TITLE
Docs should specify that categorical_enums gets sorted

### ISSUE THREAD

**Issue by arkanoid87** [corteva/geocube#33]
Docs states that the categorical_enums parameter should be a dict of lists, but then it gets sorted.

https://github.com/corteva/geocube/blob/0840e4209544146c8d653e962a923340d8534a20/geocube/vector_to_cube.py#L76

This should be stated in the documentation, as it takes the user to wrong results without warnings

**Comment by snowman2** [comment]
@arkanoid87 I agree that that should be added to the documentation. The reasoning for this functionality is to ensure the consistency of the categories. The output categories in the sorted/unique form are added to the output dataset.

**Comment by arkanoid87** [comment]
sure, but this behaviour assumes that the input categories are unknown to previous code, and that assumption was wrong in my case. Moreover docs states it wants a dict of lists, and lists are sorted.

I solved by sorting my input data by alphabetical index long before running geocube, but I had to debug the code for an hour to get down to the problem.

**Comment by snowman2** [comment]
That makes sense. I appreciate the feedback :+1:
