### ISSUE TITLE
ImportError: cannot import name 'crs_to_wkt'

### ISSUE THREAD

**Issue by j3r3m1** [corteva/geocube#57]
Hi,
I have installed geocube using conda but I have issues with the import when I do
```python
from geocube.api.core import make_geocube
```
I get the import error set as title of this issue. 

#### Installation method/steps
conda install -c conda-forge geocube 

#### Environment Information
geocube.show_version() gives the following

>geocube v0.0.15
GDAL deps:
         fiona: 1.8.18
   GDAL[fiona]: 3.1.4
      rasterio: 1.2.0
GDAL[rasterio]: 3.1.4
Python deps:
       appdirs: 1.4.4
         click: 7.1.2
      datacube: 1.8.3
     geopandas: 0.8.1
     rioxarray: 0.3.0
        pyproj: 2.6.1.post1
        xarray: 0.16.2
System:
        python: 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42)  [GCC 7.5.0]
    executable: /home/decide/miniconda2/envs/geo_env/bin/python
       machine: Linux-4.15.0-135-generic-x86_64-with-debian-buster-sid

**Comment by snowman2** [comment]
Thanks for the report :+1:
