### ISSUE TITLE
Losing data when add a raster to a geocube

### ISSUE THREAD

**Issue by MaxDragonheart** [corteva/geocube#62]
I don't know if it is a bug or my misunderstanding, but I'm following [this example](https://corteva.github.io/geocube/html/examples/zonal_statistics.html#Create-the-data-mask-by-rasterizing-the-unique-ID-of-the-vector-data) without fortune.

```
vector_in = geopandas.read_file(input_vector)
raster_in = rioxarray.open_rasterio(input_raster)

out_grid = make_geocube(
    vector_data=vector_in,
    measurements=["id"],
    like=raster_in,
)
```

When I use `out_grid["process_value"] = raster_in` and later `out_grid.to_netcdf('mydata.nc')` I see that the output has a lot of nodata. But neither `vector_in` or `raster_in` have this amount of nodata.

[Here](https://drive.google.com/file/d/1C6Fyz8jMNuLuQbQfibDo71TV0peCIIH8/view?usp=sharing) there is a QGIS project with my data.

**Comment by MaxDragonheart** [comment]
Even if I use your data from your tutorial I see a lot of nodata.

**Comment by snowman2** [comment]
Please provide the output of `geocube --show-versions`

**Comment by MaxDragonheart** [comment]
@snowman2 the version is 0.0.16

**Comment by snowman2** [comment]
@MaxDragonheart please provide the output of `geocube --show-versions`. It contains information helpful when debugging.

**Comment by MaxDragonheart** [comment]
```
geocube v0.0.16

GDAL deps:
         fiona: 1.8.18
   GDAL[fiona]: 2.4.4
      rasterio: 1.2.0
GDAL[rasterio]: 3.2.1

Python deps:
       appdirs: 1.4.4
         click: 7.1.2
      datacube: 1.8.3
     geopandas: 0.8.2
     rioxarray: 0.3.1
        pyproj: 3.0.0.post1
        xarray: 0.17.0

System:
        python: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
    executable: /home/maxdragonheart/DEV_FOLDER/MIO/DrakoNotebook/.env/bin/python3
       machine: Linux-5.8.0-45-generic-x86_64-with-glibc2.29

```

**Comment by snowman2** [comment]
> I see that the output has a lot of nodata. 

Nodata is expected for the areas that your shapes don't cover. Did you view the output netCDF in QGIS?

**Comment by MaxDragonheart** [comment]
Yes I do. [Here](https://drive.google.com/file/d/1C6Fyz8jMNuLuQbQfibDo71TV0peCIIH8/view?usp=sharing) new test data with netCDF.

I expect nodata when the area isn't coverage by raster, but not when it's covered.

**Comment by snowman2** [comment]
> I expect nodata when the area isn't coverage by raster, but not when it's covered.

The nodata values should be due to regions you input shapefiles don't cover. I haven't looked at your test data yet, but that is what I would expect with the process.

**Comment by MaxDragonheart** [comment]
> The nodata values should be due to regions you input shapefiles don't cover. I haven't looked at your test data yet, but that is what I would expect with the process.

It is possible with part of pixels, but why happen the same thing with your tutorial's data?

> Even if I use your data from your tutorial I see a lot of nodata.

**Comment by snowman2** [comment]
> It is possible with part of pixels, but why happen the same thing with your tutorial's data?

The vector data is only in a small area of what is shown. The example would likely be much better with the grid clipped to the shapefile.

```python
ssurgo_data = gpd.read_file("../../test/test_data/input/soil_data_group.geojson")
levation = rioxarray.open_rasterio(
    "zip://USGS_NED_13_n42w091_IMG.zip/USGS_NED_13_n42w091_IMG.img", masked=True
).rio.clip(ssurgo_data.geometry.values, ssurgo_data.crs).squeeze().drop("band")
elevation.name = "elevation"
```

**Comment by MaxDragonheart** [comment]
Using your data I obtain this:
![result](https://i.ibb.co/Np7fKLS/zonal-statistics-originaldata.jpg)

This is the same problem that I have with my data. Are you sure that there isn't a bug inside your code?

![result_customdata](https://i.ibb.co/XY0pDdW/zonal-statistics-mydata.jpg)

NB: this images are hosted up to one month

**Comment by snowman2** [comment]
> Are you sure that there isn't a bug inside your code?

Will need to dig into it later to see what is going on. Thanks for the images, that is helpful.

**Comment by snowman2** [comment]
I was able to reproduce the issue you demonstrated. I think it has to do with decimal precision of the coordinates when adding the DataArray to the Dataset. That being said, I checked that the `x` coordinate and `y` coordinates were the exact same for `raster_in` and `out_grid`. This is likely an issue with `xarray` and not `geocube`.

For a workaround, this got it working without the gaps for me:
```python
vector_in = geopandas.read_file("vector_data.shp")
raster_in = rioxarray.open_rasterio("raster_data.tif", masked=True).sel(band=1).drop("band")

out_grid = make_geocube(
    vector_data=vector_in,
    measurements=["id"],
    like=raster_in,
)

out_grid["process_value"] = (raster_in.dims, raster_in.values, raster_in.attrs)
```

**Comment by MaxDragonheart** [comment]
Thank you for support! 
So, do you think is useful if I open an issue on xarray reository linking this issue?

**Comment by snowman2** [comment]
> do you think is useful if I open an issue on xarray repository linking this issue?

I think it would be. Would be good to get their insight on the issue.
