### ISSUE TITLE
[Feature] Is it possible to add the funcitonability of polygonizing

### ISSUE THREAD

**Issue by CWen001** [corteva/geocube#65]
First, thank you very much for this package, which helps solve the pain point of converting Geopandas vector data to tif through xarray. May I ask if the package can also facilitate converting an Xarray dataset to Geopandas vectors (polygonizing). That would be much convenient than using gdal functions. Thank you very much.

**Comment by snowman2** [comment]
> @Meresmata Did you ever end up building any `raster->vector` functionality? I found this issue while searching for similar functionality, and ended up [creating my own implementation](https://github.com/JessicaS11/icebath/blob/main/icebath/core/build_gdf.py) to build a geodataframe using `rasterio.features.shapes` on an xarray dataset. It's highly application specific (loops through only one variable based on the time dimension) and the code still needs some cleanup, but I wanted to share in case it's helpful. Where the variable data fit into memory it was as simple as adding the transform input to `shapes()`. The trickier part was when the variable data was a dask array that didn't all fit into memory, so a geotransform needed to be constructed per-chunk and then fed into `shapes()` within a `dask.delayed` function call.

_Originally posted by @JessicaS11 in https://github.com/corteva/rioxarray/issues/159#issuecomment-801210867_

**Comment by snowman2** [comment]
This is something that I think would make sense to add to geocube if someone wanted to take a stab at it.

**Comment by Meresmata** [comment]
Raster->Vector? I normally rasterstats for it, but this is probably something completely different, from what you intended!

I never had problems that a raster fits into the memory! The think is a) perhaps you have invoke the garbage collector? That's what helps me normally, when processing several rasters after another or with multiprocessing. I never had to deal with a single raster, that was larger than my RAM!

**Comment by snowman2** [comment]
Related: https://github.com/xarray-contrib/xvec
