### ISSUE TITLE
cannot import name 'clock_gettime' from 'time' (unknown location)

### ISSUE THREAD

**Issue by bartzwemmer** [corteva/geocube#71]
`time.clock` has been removed in Python 3.8 after being deprecated in Python 3.3. The recommendation is to change clock by either `time.perf_counter` or `time.process_time`. 

This errors arises with the following code on Python 3.8.x:
`from geocube.api.core import make_geocube`

**Comment by bartzwemmer** [comment]
After researching some more, time is imported in the datacube package that you rely on. I'll report the issue there as well.

**Comment by snowman2** [comment]
Thanks for the report. Closing for the upstream issue: https://github.com/opendatacube/datacube-core/issues/1176
