### ISSUE TITLE
DOC: Missing file link in example

### ISSUE THREAD

**Issue by wakame1367** [corteva/geocube#91]
I'd like to walk through the example of zonal statistics, but step [3] is fail:
https://corteva.github.io/geocube/html/examples/zonal_statistics.html

The link to the TIF file returns a 404.
https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/n42w091/USGS_13_n42w091.tif

**Comment by snowman2** [comment]
Seems related to #73. They must have moved it again.

**Comment by baloola** [comment]
I think that this url is working
[https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/current/n42w091/USGS_13_n42w091.tif](url)

I'll open  PR if it is okay

**Comment by snowman2** [comment]
> I'll open PR if it is okay

That would be great, thanks 👍
