### ISSUE TITLE
Wrong shape of resulting Dataset when using `like` argument while rasterizing

### ISSUE THREAD

**Issue by BENR0** [corteva/geocube#93]
When rasterizing point data with `make_geocube` and handing over a template dataset to `like` the result is wrong because the width and height is switched. This is due to the wrong order of width and height in line:
https://github.com/corteva/geocube/blob/6a37df2a689936f58ffa11f1b7d66b2f81af712f/geocube/geo_utils/geobox.py#L43
in the function `geobox_from_rio` because `xds.rio.shape` returns `height, width`:
https://github.com/corteva/rioxarray/blob/20351700c851aabe557905be3a216f9479919d95/rioxarray/rioxarray.py#L825-L827

Let me know if you like me to make a PR with the fix.

**Comment by snowman2** [comment]
> Let me know if you like me to make a PR with the fix.

Yes, please. Thanks :+1:

**Comment by snowman2** [comment]
Related to https://github.com/corteva/rioxarray/pull/121
