### ISSUE TITLE
PROJ error when importing make_geocube

### ISSUE THREAD

**Issue by sbland** [corteva/geocube#96]
I get the following error when using `from geocube.api.core import make_geocube`. 

`ERROR 1: PROJ: proj_create_from_database: /home/ubu/miniconda3/envs/geoenv/share/proj/proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.`

Running `geocube --show-versions` from the cli also results in this error.
#### Environment Information

 - geocube version 0.1.2
 - rasterio version 1.2.10
 - rasterio GDAL version 3.3.2
 - fiona version 1.8.21
 - fiona GDAL version 3.4.1
 - Python version 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]
 - Operation System Information Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.17

#### Installation method
 - conda envionment with `pip install geocube`

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
cf_xarray                 0.7.0              pyhd8ed1ab_0    conda-forge
fiona                     1.8.21                   pypi_0    pypi
rasterio                  1.2.10                   pypi_0    pypi
rioxarray                 0.10.2                   pypi_0    pypi
scipy                     1.8.0            py38h56a6a73_1    conda-forge
xarray                    0.20.1             pyhd3eb1b0_1  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
active environment : geoenv
    active env location : ~/miniconda3/envs/geoenv
            shell level : 2
       user config file : ~/.condarc
 populated config files : ~/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=4.19.128=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : ~/miniconda3  (writable)
      conda av data dir : ~/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : ~/miniconda3/pkgs
                          ~/.conda/pkgs
       envs directories : ~/miniconda3/envs
                          ~/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/4.19.128-microsoft-standard ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : ~/.netrc
           offline mode : False

```
</details>

**Comment by sbland** [comment]
This seems to be caused by `from datacube.utils import geometry` in `geobox.py`.

**Comment by snowman2** [comment]
It is because the version of the PROJ database found is incompatible with the PROJ version used.

This should help debug: https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select

**Comment by snowman2** [comment]
Also, using pip install in a conda environment is discouraged as it usually leads to installation issues: https://corteva.github.io/geocube/stable/installation.html
